services:
  kpa_postgres:
    image: postgres:14
    container_name: kpa_postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  kpa_fastapi:
    build: .
    container_name: kpa_fastapi
    ports:
      - "8000:8000"
    depends_on:
      - kpa_postgres
    volumes:
      - .:/app
    environment:
      DATABASE_URL:${DATABASE_URL}

volumes:
  postgres_data:
